#!/bin/bash

if [[ !(`which deborphan`) ]]; then
		echo "You need to install deborphan to use this script" 
fi

echo "WARNING, THIS WILL REMOVE ALL ORPHAN PACKAGES"
while read -r line;
do
				sudo apt --purge remove $line -y
done < <(deborphan)

